from pydantic import BaseModel
from typing import Dict, Any

class LLMResponseAnalyzer(BaseModel):
    """
        Structured response common to all LLM providers.
        Ensures that regardless of the provider, the output follows the same schema.
        """
    threat_score: int
    reasoning_summary: str
    recommendation: str

    model_config = {
        # Providers may still emit extra keys; ignore them and keep only the canonical 3 fields.
        "extra": "ignore"
    }

    @classmethod
    def to_dict_schema(cls) -> Dict[str, Any]:
        """
        Manually builds the exact JSON Schema required by the Gemini SDK,
        avoiding incompatibilities generated by Pydantic V2 directly.
        """
        return {
            "type": "OBJECT",
            "properties": {
                "threat_score": {
                    "type": "NUMBER"
                },
                "reasoning_summary": {
                    "type": "STRING"
                },
                "recommendation": {
                    "type": "STRING"
                }
            },
            "required": [
                "threat_score",
                "reasoning_summary",
                "recommendation"
            ]
        }