from pydantic import BaseModel, Field
from typing import Dict, Any, Optional, List


class ToolCall(BaseModel):
    """Invocación unificada de una herramienta."""
    id: str
    name: str
    arguments: Dict[str, Any]


class LLMResponse(BaseModel):
    """Respuesta estandarizada que devuelve CUALQUIER adaptador de LLM."""
    content: Optional[str] = None
    tool_calls: List[ToolCall] = Field(default_factory=list)
    raw_response: Any = None  # Objeto original opcional para debugging

    @property
    def has_tool_calls(self) -> bool:
        return len(self.tool_calls) > 0

class LLMResponseAnalyzer(BaseModel):
    """
        Structured response common to all LLM providers.
        Ensures that regardless of the provider, the output follows the same schema.
        """
    threat_score: int
    reasoning_summary: str
    recommendation: str

    model_config = {
        # Providers may still emit extra keys; ignore them and keep only the canonical 3 fields.
        "extra": "ignore"
    }

    @classmethod
    def to_dict_schema(cls) -> Dict[str, Any]:
        """
        Manually builds the exact JSON Schema required by the Gemini SDK,
        avoiding incompatibilities generated by Pydantic V2 directly.
        """
        return {
            "type": "OBJECT",
            "properties": {
                "threat_score": {
                    "type": "NUMBER"
                },
                "reasoning_summary": {
                    "type": "STRING"
                },
                "recommendation": {
                    "type": "STRING"
                }
            },
            "required": [
                "threat_score",
                "reasoning_summary",
                "recommendation"
            ]
        }