from pydantic import BaseModel, Field
from typing import Dict, Any, Optional, List


class ToolCall(BaseModel):
    """Invocación unificada de una herramienta."""
    id: str
    name: str
    arguments: Dict[str, Any]


class LLMResponse(BaseModel):
    """Respuesta estandarizada que devuelve CUALQUIER adaptador de LLM."""
    content: Optional[str] = None
    tool_calls: List[ToolCall] = Field(default_factory=list)
    raw_response: Any = None  # Objeto original opcional para debugging

    @property
    def has_tool_calls(self) -> bool:
        return len(self.tool_calls) > 0

class LLMResponseAnalyzer(BaseModel):
    """
        Structured response common to all LLM providers.
        Ensures that regardless of the provider, the output follows the same schema.
        """
    threat_score: int = Field(
        ...,
        ge=0,
        le=100,
        description="Assessed threat level ranging from 0 (Safe / Benign traffic) to 100 (Critical threat / Active attack).",
    )
    reasoning_summary: str = Field(
        ...,
        description=(
            "Detailed step-by-step reasoning formatted in rich Markdown. "
            "Must provide clear justification in ALL cases, whether a threat is detected or the log stream is confirmed benign. "
            "Use bold text, bullet points, and inline code snippets for logs or IP addresses where appropriate."
        ),
    )

    recommendation: str = Field(
        ...,
        description=(
            "Actionable next steps formatted in rich Markdown. "
            "If threat_score > 0, detail specific mitigation steps, IP blocks, or firewall rule adjustments. "
            "If no threat is found (threat_score = 0), explicitly state 'No immediate action required' with routine monitoring recommendations."
        ),
    )

    model_config = {
        # Providers may still emit extra keys; ignore them and keep only the canonical 3 fields.
        "extra": "ignore"
    }

    @classmethod
    def to_dict_schema(cls) -> Dict[str, Any]:
        """
        Manually builds the exact JSON Schema required by the Gemini SDK,
        avoiding incompatibilities generated by Pydantic V2 directly.
        """
        return {
            "type": "OBJECT",
            "properties": {
                "threat_score": {
                    "type": "NUMBER"
                },
                "reasoning_summary": {
                    "type": "STRING"
                },
                "recommendation": {
                    "type": "STRING"
                }
            },
            "required": [
                "threat_score",
                "reasoning_summary",
                "recommendation"
            ]
        }