import copy
import logging
import google.generativeai as genai
import asyncio
from typing import Optional

from google.generativeai.types import generation_types

from core_orchestrator.domain.entities.agent.agents import LLMResponseAnalyzer
from core_orchestrator.domain.exceptions.llm_exceptions import LLMConfigurationException, LLMEmptyResponseException, \
    LLMLimitExceededException, LLMException
from core_orchestrator.domain.ports.agent.ai_providers import AiProvider
from core_orchestrator.infrastructure.adapters.ai_providers.system_instructions import get_analysis_system_instructions


logger = logging.getLogger("core_orchestrator.adapters.ai_providers.gemini_provider_adapter")
class GeminiProviderAdapter(AiProvider):
    """
    Represents a provider adapter for the Gemini AI model.

    This class facilitates interaction with the Gemini model, managing the configuration,
    authentication, and communication with the API. It provides methods for sending prompts,
    retrieving results, and performing health checks to ensure availability. The adapter
    adheres to the strict token limits and specifications required by Gemini models.
    """

    _PROVIDER_NAME = "gemini"

    def __init__(self, *, model_name: str, api_key: str, max_output_tokens: Optional[int] = None,
                 timeout: Optional[int] = None):
        """
        Initializes the GeminiProvider class for interacting with the Gemini API via a specified
        generative model and configuration.

        The GeminiProvider class configures the API connection, sets up the generation model,
        and validates the provided API key during initialization.

        Args:
            model_name (str): Specifies the name of the generative model to use with the Gemini API
            api_key (str): The API key is required for authenticating requests to the Gemini API
            max_output_tokens (Optional[int]): Limits the maximum number of tokens the model can
                output in a single response. Defaults to 4160 if not provided
            timeout (Optional[int]): Specifies the timeout duration in seconds for API requests
                Defaults to 60 seconds

        Raises:
            LLMConfigurationException: Raised when no valid API key is provided during
                initialization.
        """

        super().__init__(model_name, api_key, max_output_tokens)
        self._api_key = api_key
        self._model_name = model_name
        self._max_tokens = max_output_tokens or 4160
        self._timeout = timeout or 60

        if not self._api_key:
            raise LLMConfigurationException("Gemini API key is required.")

        genai.configure(api_key=self._api_key)
        self._base_config = generation_types.GenerationConfig(
            temperature=0.1,
            response_mime_type="application/json",
            response_schema=LLMResponseAnalyzer.to_dict_schema()
        )
        self._model = genai.GenerativeModel(
            model_name=self._model_name,
            generation_config=self._base_config,
            system_instruction=get_analysis_system_instructions()
        )
        logger.info(f"GeminiProvider initialized for model: {self._model_name}")

    async def call_model(self, prompt: str, max_tokens: Optional[int] = 12000) -> str:
        """
        Calls the Gemini API model to generate content based on the provided prompt.

        This method sends a prompt to the Gemini API model specified by the internal configuration.
        It enforces a minimum token limit to reduce the likelihood of truncated JSON responses.
        The method handles various exceptions related to timeouts, empty responses, or other API
        failures and raises domain-specific exceptions accordingly.

        Args:
            prompt (str): The input string to be processed by the Gemini model
            max_tokens (Optional[int]): The maximum number of output tokens allowed for the
                generated response. Defaults to 12.000 if not provided.

        Returns:
            str: The text response generated by the Gemini model.

        Raises:
            LLMLimitExceededException: If the API call exceeds the configured timeout limit.
            LLMEmptyResponseException: If the Gemini API returns an empty response.
            LLMException: If any other failure occurs during the API call.
        """
        # 1. Force a healthy minimum of tokens to avoid JSON truncation
        current_max_tokens = max_tokens or self._max_tokens
        if current_max_tokens < 2048:
            current_max_tokens = 4160

        try:
            logger.debug(f"Sending prompt to Gemini ({self._model_name})")

            runtime_config = copy.copy(self._base_config)
            runtime_config.max_output_tokens = current_max_tokens

            response = await asyncio.wait_for(
                asyncio.to_thread(
                    lambda: self._model.generate_content(
                        prompt,
                        generation_config=runtime_config
                    )
                ),
                timeout=float(self._timeout),
            )

            if not response or not response.text:
                logger.error("Gemini returned empty response")
                raise LLMEmptyResponseException("Empty response from Gemini API")

            logger.debug("Response received from Gemini successfully")
            return response.text.strip()

        except asyncio.TimeoutError as exc:
            logger.error("Gemini call timed out after %ss", self._timeout)
            raise LLMLimitExceededException(f"Gemini API timed out after {self._timeout}s") from exc

        except Exception as exc:
            logger.exception(f"Error in Gemini API call: {str(exc)}", exc_info=True)
            logger.error(f"prompt :\n {prompt}")
            raise LLMException(f"Gemini API failure: {str(exc)}") from exc

    @property
    def provider_name(self) -> str:
        """
        @property
        def provider_name(self) -> str:
            """
        return self._PROVIDER_NAME

    @property
    def model_name(self) -> str:
        """
        Returns the name of the model.

        This property provides access to the name of the model associated with the
        instance.

        Returns:
            str: The name of the model.
        """
        return self._model_name

    async def health_check(self) -> bool:
        """
        Checks the health of the Gemini system by performing a minimal operation to ensure that the
        model is initialized and can respond correctly to a test input.

        Returns:
            bool: True if the health check is successful, False otherwise.
        """
        try:
            logger.info("Running Gemini health check")

            # Initialize if necessary
            if self._model is None:
                genai.configure(api_key=self._api_key)
                self._model = genai.GenerativeModel(
                    model_name=self._model_name,
                    generation_config=self._base_config,
                    system_instruction=get_analysis_system_instructions()
                )

            test_prompt = '{"test": true}'
            response = await asyncio.to_thread(
                self._model.generate_content,
                f'Respond with valid JSON: {test_prompt}'
            )

            if response and response.text:
                logger.info("Gemini health check successful")
                return True
            else:
                logger.warning("Gemini health check: empty response")
                return False

        except Exception as exc:
            logger.exception(f"Gemini health check failed: {str(exc)}")
            return False

