FROM ollama/ollama:latest
 
WORKDIR /app
 
# Instalar netcat
RUN apt-get update && apt-get install -y netcat-openbsd && rm -rf /var/lib/apt/lists/*

# Copiar AMBOS Modelfiles al contenedor
COPY ModelfileForensic .
COPY ModelfileMongoTranslate .

# Levantamos Ollama, esperamos el puerto, descargamos el modelo base y creamos ambos agentes
RUN ollama serve & \
    echo "Esperando a que Ollama inicie..." && \
    while ! nc -z localhost 11434; do sleep 1; done && \
    echo "Descargando modelo base qwen2.5-coder:7b..." && \
    ollama pull qwen2.5-coder:7b && \
    \
    echo "Creando agente 1: sentinel-analyst (Forensic)..." && \
    ollama create sentinel-analyst -f ModelfileForensic && \
    \
    echo "Creando agente 2: sentinel-translator (MongoDB NLQ)..." && \
    ollama create sentinel-translator-mongodb -f ModelfileMongoTranslate && \
    \
    echo "¡Ambos modelos inyectados exitosamente en la imagen!"