"""
Abstract interface module for LLM providers.

Defines the contract that all language model providers
(Gemini, Ollama, Claude, OpenAI, etc.) must fulfill to guarantee compatibility and interchangeability.
"""

from abc import ABC, abstractmethod
from typing import Any, Dict, List, Optional
from pydantic import BaseModel
import logging

logger = logging.getLogger("mcp_servers.log_analysis_server.llm_providers.base")


class LLMResponse(BaseModel):
    """
    Structured response common to all LLM providers.
    Ensures that regardless of the provider, the output follows the same schema.
    """
    threat_score: int
    reasoning_summary: str
    recommendation: str

    model_config = {
        # Providers may still emit extra keys; ignore them and keep only the canonical 3 fields.
        "extra": "ignore"
    }

    @classmethod
    def to_dict_schema(cls) -> Dict[str, Any]:
        """
        Manually builds the exact JSON Schema required by the Gemini SDK,
        avoiding incompatibilities generated by Pydantic V2 directly.
        """
        return {
            "type": "OBJECT",
            "properties": {
                "threat_score": {
                    "type": "NUMBER"
                },
                "reasoning_summary": {
                    "type": "STRING"
                },
                "recommendation": {
                    "type": "STRING"
                }
            },
            "required": [
                "threat_score",
                "reasoning_summary",
                "recommendation"
            ]
        }


class LLMProviderInterface(ABC):
    """
    Abstract interface defining the contract for all LLM providers.
    
    Each concrete implementation (Gemini, Ollama, Claude, OpenAI) must inherit
    from this class and implement all abstract methods.
    """

    def __init__(self, config: Dict[str, Any]):
        """
        Initialize the provider with specific configuration.
        
        Args:
            config (Dict[str, Any]): Configuration dictionary with environment variables
                (may include API keys, base URLs, models, timeouts, etc.)
        """
        self.config = config
        logger.debug(f"Initializing LLM provider with configuration: {self._sanitize_config(config)}")

    @abstractmethod
    def build_analysis_prompt(self, telemetry: Any, history: List[Any]) -> str:
        """
        Dynamically generates the prompt adapted to the provider's nature.

        Each concrete provider will decide internally whether to build an
        extended descriptive prompt (e.g., Gemini) or an optimized JSON payload (e.g., Ollama).

        Args:
            telemetry (Any): Current telemetry window data.
            history (List[Any]): History of previous alerts for the IP.

        Returns:
            str: The prompt string ready to be sent to call_model().
        """
        pass

    @abstractmethod
    async def call_model(self, prompt: str, max_tokens: Optional[int] = None) -> str:
        """
        Invoke the LLM model with the provided prompt.
        
        Must return the response as a valid JSON string that can be parsed
        by validate_response().
        
        Args:
            prompt (str): Complete prompt with context, instructions and data to analyze
            max_tokens (Optional[int]): Response token limit (if applicable)
            
        Returns:
            str: Response JSON as string
            
        Raises:
            LLMException: If there is an error in the model call (timeout, auth, etc.)
        """
        pass

    @abstractmethod
    async def validate_response(self, response: str) -> LLMResponse:
        """
        Validate and parse the model response to structured LLMResponse.
        
        Ensures the response conforms to the expected schema and handles
        deviations or format errors.
        
        Args:
            response (str): JSON string from the model response
            
        Returns:
            LLMResponse: Validated object with structured response
            
        Raises:
            ValidationError: If JSON does not conform to LLMResponse schema
        """
        pass

    @property
    @abstractmethod
    def provider_name(self) -> str:
        """
        Unique provider name (lowercase).
        
        Examples: 'gemini', 'ollama', 'claude', 'openai'
        
        Returns:
            str: Provider name
        """
        pass

    @property
    @abstractmethod
    def model_name(self) -> str:
        """
        Name of the specific model being used.
        
        Examples: 'gemini-1.5-flash', 'mistral', 'claude-3-sonnet'
        
        Returns:
            str: Model name
        """
        pass

    @abstractmethod
    async def health_check(self) -> bool:
        """
        Verify that the provider is available and functional.
        
        Must make a minimal call (without significant cost) to
        verify connectivity, authentication and service availability.
        
        Returns:
            bool: True if the provider is available, False otherwise
        """
        pass

    @staticmethod
    def _sanitize_config(config: Dict[str, Any]) -> Dict[str, Any]:
        """
        Remove sensitive data (API keys, passwords) from the configuration
        for safe logging.
        
        Args:
            config (Dict[str, Any]): Original configuration
            
        Returns:
            Dict[str, Any]: Configuration with sensitive data masked
        """
        sensitive_keys = { 'api_key', 'secret', 'password', 'token', 'key'}
        sanitized = {}
        for k, v in config.items():
            if any(sensitive in k.lower() for sensitive in sensitive_keys):
                sanitized[k] = "***REDACTED***"
            else:
                sanitized[k] = v
        return sanitized


class LLMException(Exception):
    """
    Generic exception for errors related to LLM providers.
    
    Inherits from Exception and can be specifically caught for error handling
    of LLM service communication errors.
    """
    pass
