# ==========================================
# 1. FUENTES DE DATOS (SOURCES)
# ==========================================

# FUENTE 1: Tu app Web FastAPI
[sources.victim_web_logs]
  type = "file"
  include = ["/var/log/victim_app/activity.log"]
  read_from = "beginning"
  ignore_checkpoints = false


# FUENTE 2: Logs de Auditoría de MongoDB
[sources.mongo_db_logs]
  type = "file"
  include = ["/var/log/mongodb/mongod.log"]
  read_from = "beginning"
  ignore_checkpoints = false

# FUENTE 3: Logs de Sistema del Host Víctima (SSH/Auth)
[sources.host_syslogs]
  type = "file"
  include = ["/var/log/auth.log", "/var/log/secure"]
  read_from = "beginning"
  ignore_checkpoints = false

# --- Transformaciones (Procesamiento Capa por Capa) ---
[transforms.parse_and_enrich]
  type = "remap"
  inputs = ["victim_web_logs", "mongo_db_logs", "host_syslogs"]
  source = """
  # 1. RESPALDO: Guardamos el mensaje original ANTES de alterar el objeto raíz (.)
  raw_msg = .message

  # 2. Intentar parsear como JSON
  parsed, err = parse_json(.message)

  if err == null {
    # --- ESCENARIO A: Log Estructurado (Web o DB nueva) ---
    . = merge!(., parsed)

    .source_ip = compact([.network.client_ip, "127.0.0.1"])[0]
    .timestamp_utc = compact([.timestamp, to_string(now())])[0]

    del(.timestamp)
  } else {
    # --- ESCENARIO B: Log Crudo / No-HTTP ---
    .source_id = "victim-host-infrastructure"
    .timestamp_utc = to_string(now())

    # Regex protegido para TOML con doble escape
    ip_regex = r'(?P<ip>(?:[0-9]{1,3}\\.){3}[0-9]{1,3})'
    extracted, reg_err = parse_regex(.message, ip_regex)

    if reg_err == null && extracted.ip != null {
       .source_ip = extracted.ip
    } else {
       .source_ip = "0.0.0.0"
    }
  }

  # ========================================================
  # INTERSECCIÓN GLOBAL: Campos extra para TODOS los logs
  # ========================================================
  if .extra_fields == null {
    .extra_fields = {}
  }



  # ========================================================
  # LIMPIEZA DE METADATOS INTERNOS
  # ========================================================
  del(.message)
  del(.file)
  del(.source_type)
  """

# --- Sinks (Outputs en Tiempo Real) ---
[sinks.sentinel_core_http]
  type = "http"
  inputs = ["parse_and_enrich"]
  uri = "http://core:8000/api/v1/telemetry/ingest/batch"
  method = "post"
  encoding.codec = "json"
  batch.max_events = 50
  batch.timeout_secs = 60

# --- Sink de Debug ---
[sinks.debug_console]
  type = "console"
  inputs = ["parse_and_enrich"]
  encoding.codec = "json"