"""Domain entities for forensic search and report generation."""

from datetime import datetime, timezone
from typing import Any, Optional

from pydantic import BaseModel, Field


class ForensicAnalyzeRequestDTO(BaseModel):
    """
    Data Transfer Object (DTO) for handling forensic analysis requests.

    This class represents the structure and constraints required for an API request
    to perform forensic analysis. It encapsulates all the required and optional
    fields, along with validation rules for each field, ensuring that input data
    meets the expected format and constraints.
    """

    query: str = Field(..., min_length=3, max_length=1000)
    source_id: Optional[str] = Field(default=None, min_length=1, max_length=100)
    client_id: Optional[str] = Field(default=None, min_length=1, max_length=100)
    page: int = Field(default=1, ge=1)
    limit: int = Field(default=25, ge=1, le=100)
    model_id: Optional[str] = Field(
        default=None,
        description="ID of the model to use (from the models enabled for the tenant)"
    )


class ForensicHistoryQueryDTO(BaseModel):
    """
    Data Transfer Object (DTO) for handling forensic history query information.

    This class is used to encapsulate the query parameters for forensic history
    requests within the system. It ensures proper validation and structure
    of the input data, making it easier to manage and use throughout the
    application.

    Attributes:
        source_id: Optional[str]
            The unique identifier of the source. Must be a string with a length
            between 1 and 100 characters. Default is None.
        client_id: Optional[str]
            The unique identifier of the client. Must be a string with a length
            between 1 and 100 characters. Default is None.
        page: int
            The page number for paginated results. Must be an integer greater than
            or equal to 1. Default is 1.
        limit: int
            The maximum number of results per page. Must be an integer between 1
            and 100 (inclusive). Default is 10.
    """

    source_id: Optional[str] = Field(default=None, min_length=1, max_length=100)
    client_id: Optional[str] = Field(default=None, min_length=1, max_length=100)
    page: int = Field(default=1, ge=1)
    limit: int = Field(default=10, ge=1, le=100)


class ForensicAnalysisRecordDTO(BaseModel):
    """
    Represents a forensic analysis record.

    This DTO (Data Transfer Object) is designed to encapsulate the details of
    a forensic analysis process, including the query used, source and client
    information, metadata such as the creation timestamp, and analysis results.
    The object is intended to serve as a structured representation of forensic
    data for storage, reporting, or further processing.

    Attributes:
        analysis_id (str): Unique identifier for the forensic analysis
        query (str): The query string that was analyzed
        source_id (Optional[str]): Identifier for the data source of the analysis,
            if applicable
        client_id (Optional[str]): Identifier for the client who initiated the
            analysis, if applicable
        created_at_utc (datetime): Timestamp of when the record was created in
            UTC. Defaults to the current UTC time
        total_matches (int): The total count of matches identified during the
            forensic analysis. Must be greater than or equal to 0
        highlights (list[str]): List of highlighted text or matches identified
            during the analysis
        markdown_report (str): Markdown-formatted string of the diagnostic
            or explanatory report generated by the analysis
        sample_results (list[dict[str, Any]]): A list of sample results from the
            analysis, where each entry is represented as a dictionary
        llm_provider_used (Optional[str]): Name of the LLM (Large Language Model)
            provider used in the analysis, if applicable
        llm_model_used (Optional[str]): Identifier or name of the specific LLM model
            used in the analysis, if applicable
        provider_source (Optional[str]): Name of the provider source used during
            the forensic analysis, if applicable
    """

    analysis_id: str
    query: str
    source_id: Optional[str] = None
    client_id: Optional[str] = None
    created_at_utc: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    total_matches: int = Field(default=0, ge=0)
    highlights: list[str] = Field(default_factory=list)
    markdown_report: str
    sample_results: list[dict[str, Any]] = Field(default_factory=list)
    llm_provider_used: Optional[str] = None
    llm_model_used: Optional[str] = None
    provider_source: Optional[str] = None


class ForensicHistoryResponseDTO(BaseModel):
    """Paginated forensic analysis history response."""

    info: dict[str, Any]
    results: list[ForensicAnalysisRecordDTO]
